schema_version: "1.0"

models:
- synthetics:
    data_source: __tmp__
    params:
      epochs: 100
      batch_size: 64
      vocab_size: 20000
      reset_states: false
      learning_rate: 0.01
      rnn_units: 256
      dropout_rate: 0.2
      overwrite: true
      early_stopping: true
      gen_temp: 1.0
      predict_batch_size: 64
      validation_split: false
      dp: false
      dp_noise_multiplier: 0.001
      dp_l2_norm_clip: 5.0
      dp_microbatches: 1
    validators:
      in_set_count: 10
      pattern_count: 10
    generate:
      num_records: 1000
      max_invalid:
    privacy_filters:
      outliers: medium
      similarity: medium
